CAMERA:
  ANGLE_BOUND: 5
  CAMERA_DISTANCE_MAX: 150
  CAMERA_DISTANCE_MIN: 50
  FIXED_CAMERA_LENS: false
  LENS_MM: 3.4
  MAX_HEIGHT: 81
  MIN_HEIGHT: 80
  PITCH_CENTERED: false
  SENSOR_HEIGHT: 5.3
  X_RES: 640
  Y_RES: 480
HOUSING_ROTATION:
  FIXED: true
  MEAN: 45.0

RANDOM_BACKGROUND: true
RANDOM_OBJECTS: false

OSM_PARAMETER:
  POSITIONS_FROM_OSM: false
  LATITUDE: 54.34
  LONGITUDE: 7.64
  RADIUS: 10 
  GENERATE_MAP_IMAGE: false 