#Data
path: <path to dataset dir>
train: <path to train dataset>
val: <path to validation dataset>

#keypoints
kpt_shape: [7,2] #number of keypoints, number of dim
flip_idx: [0,1,2,3,4,5,6]

#classes
names:
   0: WEA